name: CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main", "dev" ]


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Instal deps
        run: pip install -r requirements.txt

      - name: Check
        run: python -m pytest